
    1.Create a vector with values ranging from 10 to 49.

    2.Create a 3x3 matrix with values ranging from 0 to 8.

    3.Create a 3x3 identity matrix.
    
    4.Create a 3x3x3 array with random values.

    5.Create a 10x10 array with random values and find the minimum and maximum values.

    6.Create a random vector of size 30 and find the mean value.

    7.Normalize a 5x5 random matrix.

    8.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

    9.Create two 3x3 matrices and compute their dot product.

    10.Given a 4x4 matrix, find its transpose.

    11.Create a 3x3 matrix and calculate its determinant.

    12.Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

    13.Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.

    14.Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.

    15.Given a 5x5 matrix, find the row-wise and column-wise sums.



In [16]:
#1. 10->49
import numpy as np

vector=np.arange(10, 50)

vector 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#2.
a3d=[
    [0,1,2],
    [3,4,5],
    [6,7,8]
]
v1=np.array(a3d)
v1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#3.
matrix=np.eye(3, dtype=int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
#4.
a=np.array([
    [12,43,342],
    [23,3424,123],
    [152,534,342,],
    [543,675,843],
    [564,343,765],
    [423,65,23]
])
a

random_numbers=np.random.randint(0, 100, size=(3,3,3), dtype=int)
random_numbers

array([[[31, 19, 29],
        [34, 58, 37],
        [63, 27, 88]],

       [[27, 54, 39],
        [97, 49, 19],
        [89, 10, 53]],

       [[ 1, 73, 42],
        [74, 38,  9],
        [76, 17, 15]]], dtype=int32)

In [ ]:
#5.
ran_num2=np.random.randint(0,100, size=(10, 10), dtype=int)
ran_num2

In [39]:
ran_num2

array([[74,  8, 15, 86,  8, 13, 54, 79, 20, 87],
       [68, 20, 58, 73, 44, 11, 65, 74, 96, 38],
       [87, 68, 27, 66, 91, 31, 83, 60, 79,  8],
       [58, 55, 95, 93, 74, 30, 41, 45, 89, 56],
       [18, 51, 43, 82, 64, 83, 84, 38, 77, 99],
       [98, 36,  7, 18, 77, 36, 21, 64, 78, 57],
       [24, 81, 98,  6, 40, 55, 79, 19,  8,  4],
       [13,  7, 21, 53, 33, 62, 13, 64, 96, 68],
       [80, 67,  6, 21, 78, 81, 39, 64, 61, 75],
       [63,  8,  7, 74, 63, 81, 35, 17,  1, 29]], dtype=int32)

In [41]:
ran_num2.max()

np.int32(99)

In [42]:
ran_num2.min()

np.int32(1)

In [ ]:
#6.

ran_num3=np.random.randint(0,10, size=(10))
ran_num3

array([4, 4, 5, 2, 0, 5, 0, 2, 2, 7], dtype=int32)

In [45]:
ran_num3.mean()

np.float64(3.1)

In [ ]:
#7.
# 1 st way:
def normalize_matrix():
    
 rand_matrix=np.random.randint(0,20, size=(5, 5))

 normalized_matrix=(rand_matrix-np.min(rand_matrix)) / (np.max(rand_matrix))

 return normalized_matrix

normalized_matrix=normalize_matrix()
print("Normalized 5x5 matrix: ")
normalized_matrix

print("-----------------")

#2 nd way:
rand_matrix2=np.random.randint(0,20, size=(5, 5))

normalized_matrix2=(rand_matrix2-np.min(rand_matrix2)) / (np.max(rand_matrix2))

print("Normalized 5x5 matrix: ")
normalized_matrix2


Normalized 5x5 matrix: 
-----------------
Normalized 5x5 matrix: 


array([[0.        , 0.31578947, 0.94736842, 0.84210526, 0.94736842],
       [0.21052632, 0.89473684, 0.21052632, 1.        , 0.63157895],
       [0.84210526, 0.84210526, 0.89473684, 0.36842105, 0.84210526],
       [0.68421053, 0.        , 1.        , 0.        , 0.10526316],
       [0.47368421, 1.        , 0.        , 0.36842105, 0.15789474]])

In [68]:
# 8.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

matrix1=np.random.randint(0,10, size=(5, 3))

matrix1

array([[6, 9, 4],
       [8, 8, 1],
       [1, 0, 0],
       [3, 1, 4],
       [4, 7, 5]], dtype=int32)

In [106]:
#9.
a=np.random.randint(0,10, size=(3,3))
b=np.random.randint(0,10, size=(3,3))
r=a*b
print("Random a:\n", a)
print("\nRandom b:\n", b)
r

Random a:
 [[0 4 9]
 [0 9 9]
 [9 4 6]]

Random b:
 [[9 7 6]
 [3 8 9]
 [6 1 7]]


array([[ 0, 28, 54],
       [ 0, 72, 81],
       [54,  4, 42]], dtype=int32)

In [104]:
#10.

r_m=np.random.randint(0, 100, size=(4, 4))
print("Random matrix:\n", r_m)

a=r_m.transpose()
print("\nTransposed Matrix:\n", a)
a=r_m.transpose()

Random matrix:
 [[72 57 27 55]
 [71 76 47  9]
 [36 14 63 22]
 [90 96 85 70]]

Transposed Matrix:
 [[72 71 36 90]
 [57 76 14 96]
 [27 47 63 85]
 [55  9 22 70]]


In [108]:
#11.
# Create a 3x3 matrix with random integers (e.g., between 0 and 10)
random_m=np.random.randint(0, 10, size=(3, 3))

det = np.linalg.det(random_m)

print("Random matrix:\n", random_m)

print("\nDeterminant:", det)

Random matrix:
 [[8 3 4]
 [4 0 7]
 [7 9 6]]

Determinant: -284.99999999999983


In [ ]:
#12.Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

A=np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
B=np.array([
    [1, 2, 3],
    [5, 6, 7],
    [9, 10, 14],
    [32,43,53]
])
B

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 14],
       [32, 43, 53]])

In [119]:
np.dot(A, B)


array([[166, 216, 271],
       [354, 460, 579],
       [542, 704, 887]])

In [121]:
#13.Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.

random_matr=np.random.randint(0, 100, size=(3, 3))

vector=np.random.randint(0, 100, size=(3, 1))

product=np.dot(random_matr,vector)
product

array([[3626],
       [3045],
       [1631]], dtype=int32)

In [ ]:
#14.Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.

A=np.random.randint(1, 20, size=(3, 3))
b=np.random.randint(1, 20, size=(3, 1))

x = np.linalg.solve(A, b)

x

array([[ 6.73426573],
       [ 2.08857809],
       [-4.77389277]])

In [128]:
#15.Given a 5x5 matrix, find the row-wise and column-wise sums.

matrix_5x5=np.random.randint(0, 10, size=(5, 5))
# Calculate row-wise sums
row_sums = np.sum(matrix_5x5, axis=1)

# Calculate column-wise sums
col_sums = np.sum(matrix_5x5, axis=0)

print("Matrix itself:\n", matrix_5x5)

print("\nRow sums:\n", row_sums)

print("\nColumn sums:\n", col_sums)

Matrix itself:
 [[9 4 9 7 4]
 [1 6 6 4 1]
 [5 5 3 4 5]
 [6 2 2 4 4]
 [7 0 4 8 3]]

Row sums:
 [33 18 22 18 22]

Column sums:
 [28 17 24 27 17]
